name: Build and Release ODInfo

on:
  push:
    tags: ['r*']  # Round-based tags (r46, r46.1, etc.)
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            executable_name: odinfo
            asset_name: odinfo-linux-x64.zip
          - os: windows-latest
            executable_name: odinfo.exe
            asset_name: odinfo-windows-x64.zip
          - os: macos-latest
            executable_name: odinfo
            asset_name: odinfo-macos-x64.zip
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies with uv
      run: |
        uv sync
        uv add pyinstaller
    
    - name: Build executable
      run: |
        uv run python build.py
    
    - name: Verify build output
      shell: bash
      run: |
        ls -la publish/odinfo/
        ls -la publish/odinfo/instance/
    
    - name: Create release archive
      shell: bash
      run: |
        cd publish
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          7z a ../${{ matrix.asset_name }} odinfo
        else
          zip -r ../${{ matrix.asset_name }} odinfo
        fi
        cd ..
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.asset_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}